language: c

env:
  global:
   - TOOLKIT_PATH=.
   - SOURCES=test/main.c
  matrix:
   - MCU=LPC11U24_301

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi

      # XXX: Travis doesn't allow libnewlib-arm-none-eabi to be installed yet
      - libstdc++-arm-none-eabi-newlib

script:
  - make --file=makefile.mk
